/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'entertainment' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
  'general' : IDL.Null,
  'sports' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'source' : IDL.Text,
  'snippet' : IDL.Text,
  'timestamp' : Time,
  'category' : Category,
  'articleUrl' : IDL.Text,
});
export const ArticleWithBookmark = IDL.Record({
  'article' : Article,
  'isBookmarked' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        Category,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkArticle' : IDL.Func([IDL.Text], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(ArticleWithBookmark)], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(ArticleWithBookmark)],
      ['query'],
    ),
  'getArticlesByCategoryOffset' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [IDL.Vec(ArticleWithBookmark)],
      ['query'],
    ),
  'getArticlesOffset' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ArticleWithBookmark)],
      ['query'],
    ),
  'getBookmarkedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ArticleWithBookmark)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'entertainment' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
    'general' : IDL.Null,
    'sports' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'source' : IDL.Text,
    'snippet' : IDL.Text,
    'timestamp' : Time,
    'category' : Category,
    'articleUrl' : IDL.Text,
  });
  const ArticleWithBookmark = IDL.Record({
    'article' : Article,
    'isBookmarked' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          Category,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkArticle' : IDL.Func([IDL.Text], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(ArticleWithBookmark)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(ArticleWithBookmark)],
        ['query'],
      ),
    'getArticlesByCategoryOffset' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [IDL.Vec(ArticleWithBookmark)],
        ['query'],
      ),
    'getArticlesOffset' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ArticleWithBookmark)],
        ['query'],
      ),
    'getBookmarkedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ArticleWithBookmark)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };